// using the REST Client VsCode's extension to test our APIs
// IMPORTANT NOTE: if we set the same variable name in different files, the last one will be used
@hostname = http://localhost:3000


### Register admin
@name_admin = admin
@email_admin = admin@admin.com
@password_admin = admin123
POST {{hostname}}/auth/register HTTP/1.1
content-Type: application/json

{
  "name": "{{name_admin}}",
  "email": "{{email_admin}}",
  "password": "{{password_admin}}",
  "role": "admin"
}

### Login admin 
@token_admin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MGI5ZDUyNjIwN2M2MWJmOTIyYTMxZiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0NTU5MTYzNywiZXhwIjoxNzQ1Njc4MDM3fQ.2vis1TRiBUETO-CpX0CxDFLMaLy_5XQrC32HYmjhMpU
POST {{hostname}}/auth/login HTTP/1.1
content-Type: application/json

{
  "email": "{{email_admin}}",
  "password": "{{password_admin}}"
}

### Get info about the logged-in admin
GET {{hostname}}/user/me HTTP/1.1
Authorization: Bearer {{token_admin}}

### Get all users (admin only)
GET {{hostname}}/user/profile HTTP/1.1
Authorization: Bearer {{token_admin}}

### Register a user - valid email
@name_user = Mario Rossi
@email_user = mario.rossi@gmail.com
@password_user = password123
POST {{hostname}}/auth/register HTTP/1.1
content-Type: application/json

{
  "name": "{{name_user}}",
  "email": "{{email_user}}",
  "password": "{{password_user}}"
}


### Login a user - valid email
POST {{hostname}}/auth/login HTTP/1.1
content-Type: application/json

{
  "email": "{{email_user}}",
  "password": "{{password_user}}"
}

### Get info about the logged-in user
@token_valid = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MDYzYzQ5ODdkZGI3MjgzZGZkOGYyNCIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ1OTUwNTIwLCJleHAiOjE3NDYwMzY5MjB9.rLdokqGmRSnVF9QUhB8eZ_y3mkfSPbj2OEZ3AcinBDY
GET {{hostname}}/user/me HTTP/1.1
Authorization: Bearer {{token_valid}}

### Updating the logged-in user profile 
PUT {{hostname}}/user/me HTTP/1.1
Authorization: Bearer {{token_valid}}
content-Type: application/json

{
  "name": "Mario Rosso",
  "email": "{{email_user}}",
  "password": "{{password_user}}"
} 

### Delete the logged-in user profile
DELETE {{hostname}}/user/me HTTP/1.1
Authorization: Bearer {{token_valid}}



### Get a specific user (by ID) - valid ID
@user_id_valid = 68063c4987ddb7283dfd8f24
GET {{hostname}}/user/profile/{{user_id_valid}} HTTP/1.1

### Get a specific user (by ID) - invalid ID
@user_id_invalid = 1234567890
GET {{hostname}}/user/profile/{{user_id_invalid}} HTTP/1.1 

### Update a specific user (by ID) - valid ID 
# PUT {{hostname}}/user/profile/{{user_id_valid}} HTTP/1.1
# content-Type: application/json

# {
#   "name": "modificato",
#   "email": "test@gmail.com" 
# }

# ### Delete a specific user (by ID) - valid ID
# @user_id_valid_eliminate = 68023fc467473b873129ee0a
# DELETE {{hostname}}/user/profile/{{user_id_valid_eliminate}} HTTP/1.1 



### Insert a new event 
@title = Partita Trento Calcio 2025
@category = sport 
@date = 2027-02-20T18:00:00.000Z
POST {{hostname}}/map/events HTTP/1.1
Authorization: Bearer {{token_valid}}
content-type: application/json

{
  "title": "{{title}}",
  "organizer": "{{user_id_valid}}",
  "description_short": "Partita di calcio amichevole",
  "description_long": "Un evento imperdibile per gli amanti del calcio. Unisciti a noi per una giornata di sport e divertimento!",  
  "image": "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?q=80&w=3072&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "location_text": "Trento, Italia",
  "location": {
    "type": "Point",
    "coordinates": [11.1230, 46.0759] 
  },
  "date": "{{date}}",
  "category": "{{category}}"
}

### Get a specific event (by ID) - valid ID
@event_id_valid = 680bb9b9d44d37f7e6208155
GET {{hostname}}/map/events/{{event_id_valid}} HTTP/1.1 

### Get a specific event (by ID) - invalid ID
@event_id_invalid = 1234567890
GET {{hostname}}/map/events/{{event_id_invalid}} HTTP/1.1 

### Update an existing event - valid ID 
PUT {{hostname}}/map/events/{{event_id_valid}} HTTP/1.1
Authorization: Bearer {{token_valid}}
content-Type: application/json

{
  "title": "Concerto di Autunno",
  "organizer": "{{user_id_valid}}",
  "description_short": "Concerto live con artisti locali",
  "description_long": "Un'intera giornata di musica dal vivo, cibo e divertimento per tutte le età.", 
  "location_text": "Roma, Italia",
  "location": {
    "type": "Point",
    "coordinates": [12.4924, 41.8902] 
  },
  "date": "{{date}}",
  "category": "{{category}}"
}


### Get all events
GET {{hostname}}/map/events HTTP/1.1 

### Get all events - with filters - only category
GET {{hostname}}/map/events?category={{category}} HTTP/1.1

### Get all events - with filters - only date
GET {{hostname}}/map/events?date={{date}} HTTP/1.1 

### Get all events - with filters - only title  (using @title_search)
@title_search = Partita
GET {{hostname}}/map/events?title={{title_search}} HTTP/1.1  

### Get all events - with filters - only location (using @title) 
GET {{hostname}}/map/events?title={{title}} HTTP/1.1  


### Get all events - with filters - both category and date
GET {{hostname}}/map/events?category={{category}}&date={{date}} HTTP/1.1

### Delete a specific event (by ID) - valid ID
DELETE {{hostname}}/map/events/{{event_id_valid}} HTTP/1.1 
Authorization: Bearer {{token_valid}}





### Create a new rating - 1 rating
POST {{hostname}}/explore/rating HTTP/1.1
Authorization: Bearer {{token_valid}}
content-Type: application/json

{
  "event_id": "{{event_id_valid}}",
  "stars": 4,
  "comment": "Ci stava bene un po' di sole in più!"
} 

### Create a new rating - 2 rating
POST {{hostname}}/explore/rating HTTP/1.1
Authorization: Bearer {{token_valid}}
content-Type: application/json

{
  "event_id": "{{event_id_valid}}",
  "user_id": "{{user_id_valid}}",
  "stars": 5,
  "comment": "Fantastico! Non vedo l'ora di tornarci."
} 

### Get all ratings of a specific event (by ID) - valid ID
GET {{hostname}}/explore/rating/{{event_id_valid}} HTTP/1.1

### Delete a specific rating (by ID) - valid ID
@rating_id_valid = 68050eb8b41a48e27e7f31e1
DELETE {{hostname}}/explore/rating/{{rating_id_valid}} HTTP/1.1
Authorization: Bearer {{token_valid}}

### Delete a specific rating (by ID) - invalid ID
@rating_id_invalid = 1234567890
DELETE {{hostname}}/explore/rating/{{rating_id_invalid}} HTTP/1.1